/* 
 * File:   pwm.h
 * Author: Jamie Starling - JamieStarling.com 
 * Comments:
 * Revision history: 
 * 
 * 
 * THE SOFTWARE IS PROVIDED ?AS IS?, WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED,INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

 
#ifndef PWM_H
#define	PWM_H

#include "arduino.h"


const uint16_t PIN_TO_PWM_DUTY_LOW_REGISTER_PGM[] =
{
	 (uint16_t) &PWM1DCL,
	 (uint16_t) &PWM2DCL,	
};

const uint16_t PIN_TO_PWM_DUTY_HIGH_REGISTER_PGM[] =
{
	 (uint16_t) &PWM1DCH,
	 (uint16_t) &PWM2DCH,	
};


void analogWrite(int8_t pin , int8_t pwmvalue);
void setPWMDutyCycle (uint8_t pin, uint8_t duty);

#endif	/* PWM_H */

