/*
 * File:   systeminit.c
 * Author: Jamie Starling - JamieStarling.com 
 *
 * Created on November 2, 2020, 8:17 PM
 * 
 * THE SOFTWARE IS PROVIDED ?AS IS?, WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED,INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */


#include "arduino.h"

void system_init(void){
    //Sets System to 16Mhz
    setSystemFSOC(MHZ16);
    
    #ifdef DELAYS_H
    //Initilizes the timer system only if included
    init_trm0();
    #endif

}
